import type { RegraGenetica } from './tipos';

export const regrasGeneticas: RegraGenetica[] = [
  {
    id: 'mama_ovario',
    palavras: ['mama', 'ovário', 'ovario'],
    aplicaSexo: 'feminino',
    idadeRecomendada: 30,
    mensagem: 'Histórico familiar de câncer de mama/ovário. Vale conversar sobre iniciar rastreio (mamografia) e avaliação com mastologista ou ginecologista a partir dos 30 anos, em vez dos 40.',
  },
  {
    id: 'colorretal',
    palavras: ['colorretal', 'cólon', 'colon', 'intestino'],
    aplicaSexo: null,
    idadeRecomendada: 40,
    mensagem: 'Histórico familiar de câncer colorretal. Vale conversar sobre iniciar rastreio (colonoscopia) a partir dos 40 anos e avaliação com gastroenterologista.',
  },
  {
    id: 'prostata',
    palavras: ['próstata', 'prostata'],
    aplicaSexo: 'masculino',
    idadeRecomendada: 45,
    mensagem: 'Histórico familiar de câncer de próstata. Vale conversar sobre avaliação urológica a partir dos 45 anos, em vez dos 50.',
  },
  {
    id: 'diabetes_tipo2',
    palavras: ['diabetes tipo 2'],
    aplicaSexo: null,
    idadeRecomendada: 30,
    mensagem: 'Histórico familiar de diabetes tipo 2. Vale conversar sobre rastreio de glicemia a partir dos 30-35 anos e acompanhamento com endocrinologista.',
  },
  {
    id: 'diabetes_tipo1',
    palavras: ['diabetes tipo 1'],
    aplicaSexo: null,
    idadeRecomendada: null,
    mensagem: 'Histórico familiar de diabetes tipo 1. Não é uma condição com rastreio por idade — vale ficar atento a sintomas (sede/urina excessiva, perda de peso) e conversar com endocrinologista se surgirem.',
  },
  {
    id: 'cardiaca',
    palavras: ['infarto', 'cardíaca', 'cardiaca', 'cardiopatia', 'coração', 'coracao'],
    aplicaSexo: null,
    idadeRecomendada: null,
    mensagem: 'Histórico familiar de doença cardíaca precoce. Vale conversar sobre avaliação cardiológica e perfil lipídico com um cardiologista.',
  },
  {
    id: 'hipertensao',
    palavras: ['hipertensão', 'hipertensao', 'pressão alta', 'pressao alta'],
    aplicaSexo: null,
    idadeRecomendada: null,
    mensagem: 'Histórico familiar de hipertensão. Vale conversar sobre acompanhamento de pressão arterial mais frequente.',
  },
  {
    id: 'colesterol',
    palavras: ['colesterol'],
    aplicaSexo: null,
    idadeRecomendada: 10,
    mensagem: 'Histórico familiar de colesterol alto. As diretrizes recomendam rastreio (perfil lipídico) já entre 9-11 anos, com reforço entre 17-21 — vale conversar com o pediatra/clínico sobre adiantar esse exame.',
  },
  {
    id: 'hipotireoidismo',
    palavras: ['hipotireoidismo'],
    aplicaSexo: null,
    idadeRecomendada: 35,
    mensagem: 'Histórico familiar de hipotireoidismo. Vale considerar exame de TSH a partir dos 35 anos (repetindo a cada 5 anos), podendo ser antes se houver sintomas.',
  },
  {
    id: 'hipertireoidismo',
    palavras: ['hipertireoidismo'],
    aplicaSexo: null,
    idadeRecomendada: 35,
    mensagem: 'Histórico familiar de hipertireoidismo. Vale considerar exame de TSH a partir dos 35 anos (repetindo a cada 5 anos), podendo ser antes se houver sintomas.',
  },
  {
    id: 'osteoporose',
    palavras: ['osteoporose'],
    aplicaSexo: null,
    idadeRecomendada: 50,
    mensagem: 'Histórico familiar de osteoporose. Vale conversar sobre adiantar a densitometria óssea para os 50 anos (em vez dos 65), especialmente para mulheres.',
  },
  {
    id: 'doenca_renal',
    palavras: ['doença renal', 'doenca renal', 'renal'],
    aplicaSexo: null,
    idadeRecomendada: 20,
    mensagem: 'Histórico familiar de doença renal. Vale conversar sobre exames de função renal (e possivelmente ultrassom) a partir dos 20 anos.',
  },
  {
    id: 'avc',
    palavras: ['avc', 'acidente vascular cerebral', 'derrame'],
    aplicaSexo: null,
    idadeRecomendada: null,
    mensagem: 'Histórico familiar de AVC. Não há uma idade específica de rastreio, mas vale reforçar o controle de fatores de risco (pressão, colesterol, tabagismo) com um médico.',
  },
  {
    id: 'cancer_outro',
    palavras: ['câncer (outro tipo)', 'cancer (outro tipo)'],
    aplicaSexo: null,
    idadeRecomendada: null,
    mensagem: 'Histórico familiar de câncer. Vale mencionar esse histórico específico ao médico, que pode orientar sobre rastreio adequado ao tipo de câncer.',
  },
  {
    id: 'saude_mental',
    palavras: ['depressão', 'depressao', 'ansiedade'],
    aplicaSexo: null,
    idadeRecomendada: null,
    mensagem: 'Histórico familiar de saúde mental (depressão/ansiedade). Vale ficar atento a sinais em si mesmo e considerar conversar com psicólogo ou psiquiatra se notar sintomas.',
  },
  {
    id: 'obesidade',
    palavras: ['obesidade'],
    aplicaSexo: null,
    idadeRecomendada: null,
    mensagem: 'Histórico familiar de obesidade. Vale manter acompanhamento nutricional e hábitos saudáveis desde cedo.',
  },
  {
    id: 'glaucoma',
    palavras: ['glaucoma'],
    aplicaSexo: null,
    idadeRecomendada: 35,
    mensagem: 'Histórico familiar de glaucoma. Vale conversar sobre adiantar o exame oftalmológico completo (com medição de pressão ocular) para os 35 anos, em vez dos 40.',
  },
];

export const tipoCondicaoLabels: Record<string, string> = {
  doenca: 'Hipótese diagnóstica',
  cirurgia: 'Cirurgia',
  internacao: 'Internação',
};

export const statusCondicaoLabels: Record<string, string> = {
  ativa: 'Ativa',
  resolvida: 'Resolvida',
  cronica: 'Crônica',
};

// Lista fechada de doenças comuns — usar termos fixos ajuda tanto na busca quanto no
// funcionamento dos Cuidados Preventivos (que procura por palavras-chave nas condições da família).
export const doencasComuns: { nome: string; categoria: string }[] = [
  { nome: 'Câncer de mama', categoria: 'Oncológica' },
  { nome: 'Câncer de ovário', categoria: 'Oncológica' },
  { nome: 'Câncer colorretal', categoria: 'Oncológica' },
  { nome: 'Câncer de próstata', categoria: 'Oncológica' },
  { nome: 'Câncer (outro tipo)', categoria: 'Oncológica' },
  { nome: 'Diabetes tipo 1', categoria: 'Endocrinológica' },
  { nome: 'Diabetes tipo 2', categoria: 'Endocrinológica' },
  { nome: 'Hipertensão (pressão alta)', categoria: 'Cardiológica' },
  { nome: 'Doença cardíaca / infarto', categoria: 'Cardiológica' },
  { nome: 'Colesterol alto', categoria: 'Cardiológica' },
  { nome: 'AVC (Acidente Vascular Cerebral)', categoria: 'Neurológica' },
  { nome: 'Asma', categoria: 'Pneumológica' },
  { nome: 'Alergia', categoria: 'Alergológica' },
  { nome: 'Hipotireoidismo', categoria: 'Endocrinológica' },
  { nome: 'Hipertireoidismo', categoria: 'Endocrinológica' },
  { nome: 'Depressão', categoria: 'Psiquiátrica' },
  { nome: 'Ansiedade', categoria: 'Psiquiátrica' },
  { nome: 'Epilepsia', categoria: 'Neurológica' },
  { nome: 'Artrite / Artrose', categoria: 'Reumatológica/Ortopédica' },
  { nome: 'Osteoporose', categoria: 'Reumatológica/Ortopédica' },
  { nome: 'Obesidade', categoria: 'Endocrinológica' },
  { nome: 'Doença renal', categoria: 'Nefrológica' },
  { nome: 'Doença de Alzheimer', categoria: 'Neurológica' },
  { nome: 'Doença de Parkinson', categoria: 'Neurológica' },
  { nome: 'Enxaqueca', categoria: 'Neurológica' },
  { nome: 'Glaucoma', categoria: 'Oftalmológica' },
  { nome: 'Catarata congênita', categoria: 'Oftalmológica' },
  { nome: 'Degeneração macular', categoria: 'Oftalmológica' },
  { nome: 'Retinose pigmentar', categoria: 'Oftalmológica' },
  { nome: 'Daltonismo (deficiência de percepção de cores)', categoria: 'Oftalmológica' },
  { nome: 'Alta miopia', categoria: 'Oftalmológica' },
  { nome: 'Dor de barriga', categoria: 'Sintomas comuns (sem diagnóstico fechado)' },
  { nome: 'Dor de cabeça', categoria: 'Sintomas comuns (sem diagnóstico fechado)' },
  { nome: 'Dor de ouvido', categoria: 'Sintomas comuns (sem diagnóstico fechado)' },
  { nome: 'Dor de garganta', categoria: 'Sintomas comuns (sem diagnóstico fechado)' },
  { nome: 'Febre', categoria: 'Sintomas comuns (sem diagnóstico fechado)' },
  { nome: 'Tosse', categoria: 'Sintomas comuns (sem diagnóstico fechado)' },
  { nome: 'Resfriado / Virose', categoria: 'Sintomas comuns (sem diagnóstico fechado)' },
  { nome: 'Vômito', categoria: 'Sintomas comuns (sem diagnóstico fechado)' },
  { nome: 'Diarreia', categoria: 'Sintomas comuns (sem diagnóstico fechado)' },
  { nome: 'Reação alérgica (sem diagnóstico fechado)', categoria: 'Sintomas comuns (sem diagnóstico fechado)' },
  { nome: 'Dor muscular', categoria: 'Sintomas comuns (sem diagnóstico fechado)' },
  { nome: 'Mal-estar geral', categoria: 'Sintomas comuns (sem diagnóstico fechado)' },
  { nome: 'Outra doença (especificar)', categoria: 'Outra' },
];

export const categoriasDoencas: string[] = Array.from(new Set(doencasComuns.map((d) => d.categoria))).sort();
